server:
  port: 8080

spring:
  application:
    name: excel
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
