server:
  port: 8080

spring:
  application:
    name: excel
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      suffix: .html
      prefix: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.41.126s:1111/eureka/
